### ISSUE TITLE
Japanese language install broken

### ISSUE THREAD

**Issue by unchartedpopsicle** [Vanilla-OS/iso-builder#68]
### Issue Description

Yep, another language installer issue :)
Installing Japanese through the Gnome settings language manager, "Mozc Setup" is also installed, which throws a decent few errors and is not removed if you remove japanese again.

To get rid of it you have to remove several packages (ibus-mozc mozc-data mozc-server mozc-utils-gui) through ABRoot.

The errors I get are "Failed to get current config values" and "Cannot start conversion engine. Please restart your computer." when opening Mozc Setup. "Failed to update config" when trying to change settings, and "Execution of "gkbd-keyboard-display" failed: Command not found" when trying to show keyboard layout through its tray icon.

### Steps to Reproduce

Install Japanese language through gnome-language-selector
Reboot
Open Mozc Setup 

### On what version of Vanilla OS this happens?

22.10

**Comment by nonetrix** [comment]
Same issue when I tried to install it

**Comment by azu0609** [comment]
Same issue on vm, used r7.5 iso

**Comment by azu0609** [comment]
OK, i managed to working by install fcitx to container using:

1. Enter container with `apx enter`
2. In container, run 'sudo apt install fcitx5-mozc libcanberra-gtk*'
3. Exit container, then run `apx export fcitx5` to export
4. Add to startup using: `cp ~/.local/share/applications/apx_managed-org.fcitx.Fcitx5.desktop ~/.config/autostart/`
5. Add "kimpanel" extensions using extensions manager and reboot
6. Congratulation! fcitx5-mozc is now working on Vanilla OS!

![Screenshot from 2023-02-27 19-40-55](https://user-images.githubusercontent.com/91050580/221544415-c4d237cb-c728-4bba-a6b3-7322084c544e.png)

**Comment by nonetrix** [comment]
Wasn't there a guide someone wrote here to fix it? I swear it was here a second ago, did they delete their comment or something? I assume it's out of date in that case I guess? Anyway I just reinstalled thinking I could just follow that guide, I guess I will just go back to using the browser extension which is a decent work around anyway for now

https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab/related

**Comment by unchartedpopsicle** [comment]
@nonetrix yep, @azu0609 seems to have deleted this:

    OK, i managed to working by install fcitx to container using:

    Enter container with apx enter
    In container, run 'sudo apt install fcitx5-mozc libcanberra-gtk*'
    Exit container, then run apx export fcitx5 to export
    Add to startup using: cp ~/.local/share/applications/apx_managed-org.fcitx.Fcitx5.desktop ~/.config/autostart/
    Add "kimpanel" extensions using extensions manager and reboot
    Congratulation! fcitx5-mozc is now working on Vanilla OS!

along with a screenshot which I won't share, in case there was something in it that made them delete the comment.
I've not tested the fix myself. 
@azu0609, hope it's alright that I reposted this.

**Comment by azu0609** [comment]
@unchartedpopsicle Thanks for posting! I accidentally deleted comment and forgot comment body :(

**Comment by nonetrix** [comment]
Kinda works couldn't get it to type anything but it shows up

**Comment by azu0609** [comment]
Do you added the mozc in fcitx settings?
i forgot to add this into guide

**Comment by nonetrix** [comment]
I did but seems to only work in gnome shell search, I think this honestly is more due to some environment variable not being set or whatever I will try this later sorry

**Comment by fenglengshun** [comment]
I'm not currently using vanilla, but so far I managed to make fcitx5-mozc work with [home-manager](https://julianhofer.eu/blog/01-silverblue-nix/#home-manager):

<details><summary>Enabling fcitx5-mozc via home-manager</summary><p>

```
{ config, pkgs, ... }:

{

  home.packages = with pkgs; [
    fcitx5-gtk
    libsForQt5.fcitx5-qt
    # ...
  ];

  # enable fcitx5 as input method, with mozc for Japanese IME
  i18n.inputMethod = {
    enabled = "fcitx5";
    fcitx5.addons = with pkgs; [ fcitx5-mozc ];
}
```

</p></details>

Note that I also have home-manager install bash/zsh and manage my .profile/.bashrc/.zshrc:

<details><summary>Enabling shell management in home-manager</summary><p>

```
{ config, pkgs, ... }:

{

  # allows home-manager to manage bash
  programs.bash = {
    enable = true;
    enableCompletion = true;
  };
  # allows home-manager to manage zsh, with plugins, and oh-my-zsh management
  programs.zsh = {
    enable = true;
    autocd = true;
    history.expireDuplicatesFirst = true;
    historySubstringSearch.enable = true;
    enableAutosuggestions = true;
    enableCompletion = true;
    enableSyntaxHighlighting = true;
    initExtra = "[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh";
    oh-my-zsh = {
      enable = true;
      custom = "$HOME/.oh-my-zsh/custom/plugins";
      plugins = [ "git" "zsh-autosuggestions" "zsh-history-substring-search" "zsh-syntax-highlighting" ];
      theme = "powerlevel10k/powerlevel10k";
    };
  };

}
```

</p></details>

Reference: https://nix-community.github.io/home-manager/options.html#opt-i18n.inputMethod.enabled

**Comment by VirtuousCrane** [comment]
As of August, 2023, this is what I did to get fcitx5-mozc to work:

First, do everything according to this comment:


> @nonetrix yep, @azu0609 seems to have deleted this:
> 
> ```
> OK, i managed to working by install fcitx to container using:
> 
> Enter container with apx enter
> In container, run 'sudo apt install fcitx5-mozc libcanberra-gtk*'
> Exit container, then run apx export fcitx5 to export
> Add to startup using: cp ~/.local/share/applications/apx_managed-org.fcitx.Fcitx5.desktop ~/.config/autostart/
> Add "kimpanel" extensions using extensions manager and reboot
> Congratulation! fcitx5-mozc is now working on Vanilla OS!
> ```
> 
> along with a screenshot which I won't share, in case there was something in it that made them delete the comment. I've not tested the fix myself. @azu0609, hope it's alright that I reposted this.

Then, open up the "Fcitx 5 Configuration" application and add "Mozc" to your "current input method" column.
Apply the settings, then press Ok.

By this point, you should now be able to type in Japanese on your default GNOME applications (switch input method via Ctrl + Space). However, you will still not be able to type in Japanese in third-party applications, such as firefox.

To enable fcitx5-mozc in third-party applications, open your ".profile" file in your home directory and append these lines to the end of the file:

```
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
```
_Ref: https://wiki.archlinux.org/title/Fcitx5#Integration_

Reboot your device. It should now work in all applications.

**Comment by nonetrix** [comment]
Should be included by default imo or easy to install, Fedora already has it installed. Maybe for Vanilla OS Orchid 2?

**Comment by VirtuousCrane** [comment]
As of July 31st, 2024 (Just a few days after **Vanilla OS 2** released), you should now be able to install the GNOME (Anthy) Japanese keyboard by doing the following:

- Enter the following commands:
```
abroot pkg add ibus ibus-anthy
abroot pkg apply
```

- Restart the computer
- Open Settings > Keyboard > Add input source > Japanese > Japanese (Anthy)
- Further configurations and key bindings can be done by accessing the preferences menu of the keyboard:

![Screenshot from 2024-07-31 19-56-05](https://github.com/user-attachments/assets/bf783319-3e50-41bc-8b90-0ad911c46f03)
<br>
<br>
~_As an alternative, you can also install **ibus-mozc**, instead of ibus-anthy_~
Edit (August 4th, 2024): As mentioned by 0chroma, it seems that currently, there is a bug in which ibus-mozc doesn't seem to be working correctly

**Comment by nonetrix** [comment]
No reason to use Anthy in my opinion but should work probably

**Comment by 0chroma** [comment]
I followed @VirtuousCrane's suggestions but with ibus-mozc, and am still getting the same errors:
"Failed to get current config values."
"Cannot start conversion engine. Please restart your computer."

potentially related issue with same error: https://github.com/google/mozc/issues/72

Seems like for some reason there's an issue between `mozc_server` and `mozc_tool`. Here's a relevant part of an strace log from `mozc_server`:

```
[pid  6566] 01:25:17 openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 6
[pid  6566] 01:25:17 newfstatat(6, "", {st_mode=S_IFREG|0644, st_size=2670, ...}, AT_EMPTY_PATH) = 0
[pid  6566] 01:25:17 openat(AT_FDCWD, "/dev/shm/sem.fc32c9369a38", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
strace: Process 6569 attached
[pid  6566] 01:25:17 openat(AT_FDCWD, "/proc/self/task/6569/comm", O_RDWR) = 6
[libprotobuf ERROR google/protobuf/message_lite.cc:133] Can't parse message of type "mozc.commands.Input" because it is missing required fields: type
[libprotobuf ERROR google/protobuf/message_lite.cc:133] Can't parse message of type "mozc.commands.Input" because it is missing required fields: type
```

**Comment by 0chroma** [comment]
installing `ibus-mozc` and running `killall mozc_server && /usr/lib/mozc/mozc_server` from a container seems to work. Not sure why it's not working on the host system though.

**Comment by 0chroma** [comment]
I have a feeling this has something to do with how the protobuf library is being linked with mozc, especially since it has binaries on weird paths like `/usr/lib/mozc/`

has this kind of issue come up in the past at all with how VanillaOS handles dynamic linking?

**Comment by 0chroma** [comment]
thinking about this a little more. It definitely seems to be an ipc issue, I'm wondering if maybe it could be perm related? maybe IPC is more permissive inside the distrobox container? https://github.com/Vanilla-OS/micro-distrobox/blob/b16a288d0af366c5e2255f325d0f92533b2b4b69/usr/lib/apx/distrobox-create#L657

**Comment by 0chroma** [comment]
For anyone still finding this, I wrote a script to automate the process:

```bash
#!/bin/sh
apx subsystems new -n mozc -s vanilla
apx mozc install mozc-server
mkdir -p ~/.config/autostart
cat << EOF > ~/.config/autostart/mozc-server.desktop
[Desktop Entry]
Type=Application
Exec=apx mozc run /usr/lib/mozc/mozc_server
Name=MOZC Server
Comment=Starts the MOZC server via apx
X-GNOME-Autostart-enabled=true
EOF
chmod +x ~/.config/autostart/mozc-server.desktop
```
