### ISSUE TITLE
Timezone doesn't automatically set

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#93]
### Issue Description

Timezone doesn't automatically set even after setting location permissions 

### Steps to Reproduce

- open settings
- set automatic time and timezone 
- done

### On what version of Vanilla OS this happens?

22.10

### Additional Information

- running release 4
- also don't have the "clocks" flatpak installed. 

![Screenshot from 2023-01-17 12-30-04](https://user-images.githubusercontent.com/122128828/212970084-1013a0c6-1659-4639-9b46-64a1639ddbd3.png)

**Comment by kbdharun** [comment]
~~This has been fixed in r5.~~ This seems to be a different issue, hmm.

(Offtopic: We figured out the Jekyll Installation steps and will add it tomorrow, sorry for the delay. I was kinda busy and Monster has exams)

**Comment by ghost** [comment]
> This has been fixed in r5.
> 
> (Offtopic: We figured out the Jekyll Installation steps and will add it tomorrow, sorry for the delay. I was kinda busy and Monster has exams)

That's great! I've been just deploying my sites lol, not even locally testing it. Just winging it. No worries you guys got a lot on your hands making 3 major os tools

**Comment by kbdharun** [comment]
This seems to be resolved since the last release. Can you check if you still face it in r8?

**Comment by ghost** [comment]
> This seems to be resolved since the last release. Can you check if you still face it in r8?

Still an issue my Timezone is EST 
![image](https://user-images.githubusercontent.com/122128828/221649126-ed37a4f3-6c8f-4cc0-932a-5d556d3c9cb5.png)
![image](https://user-images.githubusercontent.com/122128828/221649231-4c0bb100-cc19-44c1-8492-199ccf13d27e.png)
